server:
  port: 8090

spring:
  application:
    name: "spring boot test"
  datasource:
    url: jdbc:mysql://9.135.248.199:3306/mybatis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: sjzrf@9453JEaC
    driver-class-name: com.mysql.cj.jdbc.Driver
people:
  student:
    name: "qpointwang"
    age: 25
  teacher:
    name: "xianzhouwang"
    age: 25

  